[package]
name = "pgserver"
edition.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
async-trait.workspace = true
common = { path = "../../core/common" }
datafusion.workspace = true
datafusion-postgres = "0.12.2"
dataset-store = { path = "../../core/dataset-store" }
datasets-common = { path = "../../core/datasets-common" }
metadata-db = { path = "../../core/metadata-db" }
thiserror.workspace = true
tokio = { workspace = true, features = ["net"] }
tracing.workspace = true
