import * as HashSet from "effect/HashSet"

export const foundryOutputExludeList = HashSet.make(
  "Base.sol/**",
  "Common.sol/**",
  "Components.sol/**",
  "IERC165.sol/**",
  "IERC20.sol/**",
  "IERC721.sol/**",
  "IMulticall2.sol/**",
  "IMulticall3.sol/**",
  "MockERC20.sol/**",
  "MockERC721.sol/**",
  "Script.sol/**",
  "StdAssertions.sol/**",
  "StdChains.sol/**",
  "StdCheats.sol/**",
  "StdError.sol/**",
  "StdInvariant.sol/**",
  "StdJson.sol/**",
  "StdMath.sol/**",
  "StdStorage.sol/**",
  "StdStyle.sol/**",
  "StdToml.sol/**",
  "StdUtils.sol/**",
  "Test.sol/**",
  "Vm.sol/**",
  "build-info/**",
  "console.sol/**",
  "console2.sol/**",
  "safeconsole.sol/**",
  "**.s.sol/*.json",
  "**.t.sol/*.json",
)
